# Parameters:
# 1 - dimension assignment class
# 2 - dimension assignment property
# 3 - value individual
# 4 - formal dimension individual
# 5 - context individual
#
# expects inference on dimension assignment class inheritance

PREFIX cm:      <http://dei.polimi.it/dbgroup/pedigree/context-model.owl#>
PREFIX rdf:     <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

SELECT ?assignmentIndividual
WHERE 
{
	?assignmentIndividual rdf:type <%1$s> .
	?assignmentIndividual <%2$s> <%3$s> .
	?assignmentIndividual cm:assignmentDimension <%4$s> .
	<%5$s> cm:dimensionAssignment ?assignmentIndividual
}