PREFIX cm:      <http://dei.polimi.it/dbgroup/pedigree/context-model.owl#>
PREFIX owl:     <http://www.w3.org/2002/07/owl#>
PREFIX rdf:     <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs:    <http://www.w3.org/2000/01/rdf-schema#>

SELECT ?assignmentClass ?assignmentProperty ?valuesClass ?formalDimension
WHERE 
{
#	?assignmentClass rdf:type owl:Class .
	?assignmentClass owl:equivalentClass ?equiv .
	?equiv owl:intersectionOf ?int .
	?int rdf:rest ?int2 .
	?int2 rdf:first ?restr .
#	?restr rdf:type owl:Restriction .
	?restr owl:onProperty cm:assignmentDimension .
	?restr owl:hasValue ?formalDimension .
#	?formalDimension rdf:type cm:FormalDimension .
#	?assignmentProperty rdf:type rdf:Property .
	?assignmentProperty rdfs:subPropertyOf cm:dimensionAssignmentValue .
	?assignmentProperty rdfs:domain ?assignmentClass .
	?assignmentProperty rdfs:range ?valuesClass .
#	?valuesClass rdf:type owl:Class .
#	?valuesClass rdfs:subClassOf cm:DimensionValue
}